export const ADD_SCORE = 'ADD_SCORE'
export const CLEAR_SCORE = 'CLEAR_SCORE'
export const CHECK_WALLET_EXT = 'CHECK_WALLET_EXT'
export const GET_USER_ADDRESS = 'GET_USER_ADDRESS'
export const SET_USER_ADDRESS = 'SET_USER_ADDRESS'
export const GET_STORE = 'GET_STORE'
export const SET_STORE = 'SET_STORE'